### ISSUE TITLE
Crash when connecting Portal after clicking on "Open an existing organization"

### ISSUE THREAD

**Issue by Thegaram** [Conflux-Network-Global/aragon-client#18] opened 2021-04-23 03:15 UTC
**Describe the bug**

When I try to connect my wallet on the open org page it crashes.

**To Reproduce**
1. Click on "Open an existing organization"
2. Connect to Conflux Portal.

**Expected behavior**

Should not crash.

**Screenshots**

![image](https://user-images.githubusercontent.com/7571518/115813089-1fd91e00-a425-11eb-8037-fc94bb675506.png)

**Comment by H34D** [comment] 2021-05-04 09:18
This is caused by the react spring framework (https://github.com/pmndrs/react-spring/issues/576) one workaround is to upgrade it to the version v9 (from v7). The impact of upgrading this is not very clear. If this has priority i can take a look into it.

**Comment by Thegaram** [comment] 2021-05-04 15:22
I believe this might have been introduced by the change that prevents users from opening organizations without connecting their wallets (#5). Reverting that change might resolve this issue.

**Comment by H34D** [comment] 2021-05-05 08:00
i reverted the change of #5 locally, still the same result.

**Comment by Thegaram** [comment] 2021-05-05 08:28
Hmm interesting. All I can say is that it's different behavior from the old version (http://aragontest.confluxnetwork.org) so I'd consider it a regression.

**Comment by H34D** [comment] 2021-05-11 09:59
fixed by updating to the latest version of use-wallet

**Closed as completed by H34D** 2021-05-11 09:59 UTC
Labels: bug
